---
- hosts: all
  gather_facts: no
  vars_files: banner.cfg

  tasks:
    - name: Gather all legacy facts
      cisco.ios.ios_facts:
        gather_subset: all
        
    - name: Set banner for Cisco IOS
      cisco.ios.ios_banner:
        state: present
        banner: motd
        text: "{{ cfg }}"
      when: ansible_network_os == 'ios'
    
    - name: Set banner for Cisco NX-OS
      cisco.nxos.nxos_banner:
        state: present
        banner: motd
        text: "{{ cfg }}"
      when: ansible_network_os == 'nxos'

    - name: Set banner for Cisco IOS XR
      cisco.iosxr.iosxr_banner:
        state: present
        banner: motd
        text: "{{ cfg }}"
      when: ansible_network_os == 'iosxr'
