---
- name: Linux Server Update
  hosts: all
  become: yes
  gather_facts: yes
  connection: ssh
  tasks:
  - name: Debian update
    apt:
      update_cache: yes
      upgrade: 'no'
    when: ansible_facts['os_family'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"

#    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: RHEL update
    yum:
      name: '*'
      state: latest
    when: ansible_facts['os_family'] == "RedHat"
 #   when: ansible_distribution == "RedHat"
   
