---
- hosts: all
  #stratgy: free
  gather_facts: no
  tasks:

  - name: Gather all legacy facts
    cisco.ios.ios_facts:
      gather_subset: all

  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: System {{ ansible_net_hostname }} with serial {{ ansible_net_serialnum | default("UNDEFINED") }} and model {{ ansible_net_model}} is at version {{ ansible_net_version }}
