---
- name: Update Windows Computer
  hosts: windows_computer
  gather_facts: false

  tasks:
    - name: Install Windows Updates
      win_windowsupdate:
        check_for_updates: true
        notify:
          - Restart Windows

    - name: Reboot Windows
      win_reboot:
        msg: "Windows needs to be restarted for updates to take effect."
      when: ansible_network.status == 'offline'

    - name: Download Updates
      win_windowsupdate:
        download_updates: true

    - name: Install Downloaded Updates
      win_windowsupdate:
        install_updates: true
